=== apache/xerces2-j/docs/design.dtd
<?xml encoding='US-ASCII'?>

<!-- overall organization -->
<!ELEMENT design (note*,types*,category*)>
<!ELEMENT types (category)*>
<!ELEMENT category (note*,(class|interface)*)>
<!ATTLIST category name    CDATA   #REQUIRED
                   package NMTOKEN #IMPLIED
>

<!-- markup -->
<!ELEMENT note (#PCDATA)>

<!-- types -->
<!ENTITY % types 'array|primitive|reference|collection'>
<!ELEMENT array (note*,(primitive|reference))>
<!ATTLIST array dimension CDATA '1'>
<!ELEMENT primitive EMPTY>
<!ATTLIST primitive type (long|int|short|char|boolean) #REQUIRED>
<!ELEMENT reference EMPTY>
<!ATTLIST reference idref IDREF #REQUIRED>
<!ELEMENT collection (note*,collector,items)>
<!ELEMENT collector (%types;)>
<!ELEMENT items (%types;)>

<!-- sections -->
<!ENTITY % visibility 'public|private|protected'>
<!ELEMENT constant (note*,(%types;))>
<!ATTLIST constant name       NMTOKEN        #REQUIRED
                   value      CDATA          #IMPLIED
                   visibility (%visibility;) 'public'
>
<!ELEMENT field (note*,(%types;))>
<!ATTLIST field name       NMTOKEN        #REQUIRED
                visibility (%visibility;) 'protected'
>
<!ELEMENT constructor (note*,param*,throws*)>
<!ATTLIST constructor visibility (%visibility;) 'public'>
<!ELEMENT method (note*,param*,returns?,throws*)>
<!ATTLIST method name       NMTOKEN        #REQUIRED
                 visibility (%visibility;) 'public'
>
<!ELEMENT param (note*,(%types;))>
<!ATTLIST param name NMTOKEN #REQUIRED>
<!ELEMENT returns (note*,(%types;))>
<!ELEMENT throws (note*,reference)>

<!-- objects -->
<!ELEMENT class (note*,extends?,implements*,constant*,field*,constructor*,method*)>
<!ATTLIST class id         ID             #REQUIRED 
                name       NMTOKEN        #REQUIRED
                visibility (%visibility;) #FIXED 'public'
>
<!ELEMENT interface (note*,extends*,constant*,method*)>
<!ATTLIST interface id         ID             #REQUIRED
                    name       NMTOKEN        #REQUIRED
                    visibility (%visibility;) #FIXED 'public'
>
<!ELEMENT extends (note*,reference)>
<!ELEMENT implements (note*,reference)>

=== apache/xerces2-j/design/xml/design.xml
<?xml version='1.0' encoding='US-ASCII'?>
<!-- $Id$ -->
<!DOCTYPE design SYSTEM 'design.dtd' [
<!ENTITY package 'org.apache.xerces'>
]>
<design name='Xerces-J 2.0'>
 <date>$Date$</date>

 <!-- TYPES -->
 <types>
  <category name='Java Language'>
   <class id='java-exception' name='Exception'/>
   <class id='java-object' name='Object'/>
   <class id='java-string' name='String'/>
   <interface id='java-cloneable' name='Cloneable'/>
  </category>
  <category name='Java I/O' package='java.io'>
   <class id='java-io-exception' name='IOException'/>
   <class id='java-io-reader' name='Reader'/>
  </category>
  <category name='Java Utils' package='java.util'>
   <class id='java-empty-stack-exception' name='EmptyStackException'/>
   <class id='java-hashtable' name='Hashtable'/>
   <class id='java-locale' name='Locale'/>
   <class id='java-missing-resource-exception' name='MissingResourceException'/>
   <class id='java-stack' name='Stack'/>
   <class id='java-vector' name='Vector'/>
  </category>
  <category name='Document Object Model' package='org.w3c.dom'>
   <interface id='dom-document' name='Document'/>
  </category>
  <category name='Simple API for XML' package='org.xml.sax'>
   <class id='sax-exception' name='SAXException'/>
   <class id='sax-input-source' name='InputSource'/>
   <class id='sax-not-recognized-exception' name='SAXNotRecognizedException'/>
   <class id='sax-not-supported-exception' name='SAXNotSupportedException'/>
   <class id='sax-parse-exception' name='SAXParseException'/>
   <interface id='sax-attribute-list' name='AttributeList'/>
   <interface id='sax-attributes' name='Attributes'/>
   <interface id='sax-content-handler' name='ContentHandler'/>
   <interface id='sax-document-handler' name='DocumentHandler'/>
   <interface id='sax-dtd-handler' name='DTDHandler'/>
   <interface id='sax-entity-resolver' name='EntityResolver'/>
   <interface id='sax-error-handler' name='ErrorHandler'/>
   <interface id='sax-locator' name='Locator'>
    <method name='getPublicId'>
     <returns>
      <reference idref='java-string'/>
     </returns>
    </method>
    <method name='getSystemId'>
     <returns>
      <reference idref='java-string'/>
     </returns>
    </method>
    <method name='getLineNumber'>
     <returns>
      <primitive type='int'/>
     </returns>
    </method>
    <method name='getColumnNumber'>
     <returns>
      <primitive type='int'/>
     </returns>
    </method>
   </interface>
   <interface id='sax-parser' name='Parser'>
    <method name='parse'>
     <param name='systemId'>
      <reference idref='java-string'/>
     </param>
     <throws>
      <reference idref='java-io-exception'/>
     </throws>
     <throws>
      <reference idref='sax-exception'/>
     </throws>
    </method>
    <method name='parse'>
     <param name='inputSource'>
      <reference idref='sax-input-source'/>
     </param>
     <throws>
      <reference idref='java-io-exception'/>
     </throws>
     <throws>
      <reference idref='sax-exception'/>
     </throws>
    </method>
    <method name='setLocale'>
     <param name='locale'>
      <reference idref='java-locale'/>
     </param>
     <throws>
      <reference idref='sax-exception'/>
     </throws>
    </method>
    <method name='setEntityResolver'>
     <param name='entityResolver'>
      <reference idref='sax-entity-resolver'/>
     </param>
    </method>
    <method name='setDocumentHandler'>
     <param name='documentHandler'>
      <reference idref='sax-document-handler'/>
     </param>
    </method>
    <method name='setDTDHandler'>
     <param name='dtdHandler'>
      <reference idref='sax-dtd-handler'/>
     </param>
    </method>
    <method name='setErrorHandler'>
     <param name='errorHandler'>
      <reference idref='sax-error-handler'/>
     </param>
    </method>
   </interface>
   <interface id='sax-xmlreader' name='XMLReader'>
    <method name='parse'>
     <param name='systemId'>
      <reference idref='java-string'/>
     </param>
     <throws>
      <reference idref='java-io-exception'/>
     </throws>
     <throws>
      <reference idref='sax-exception'/>
     </throws>
    </method>
    <method name='parse'>
     <param name='inputSource'>
      <reference idref='sax-input-source'/>
     </param>
     <throws>
      <reference idref='java-io-exception'/>
     </throws>
     <throws>
      <reference idref='sax-exception'/>
     </throws>
    </method>
    <method name='setEntityResolver'>
     <param name='entityResolver'>
      <reference idref='sax-entity-resolver'/>
     </param>
    </method>
    <method name='getEntityResolver'>
     <returns>
      <reference idref='sax-entity-resolver'/>
     </returns>
    </method>
    <method name='setContentHandler'>
     <param name='contentHandler'>
      <reference idref='sax-content-handler'/>
     </param>
    </method>
    <method name='getContentHandler'>
     <returns>
      <reference idref='sax-content-handler'/>
     </returns>
    </method>
    <method name='setDTDHandler'>
     <param name='dtdHandler'>
      <reference idref='sax-dtd-handler'/>
     </param>
    </method>
    <method name='getDTDHandler'>
     <returns>
      <reference idref='sax-dtd-handler'/>
     </returns>
    </method>
    <method name='setErrorHandler'>
     <param name='errorHandler'>
      <reference idref='sax-error-handler'/>
     </param>
    </method>
    <method name='getErrorHandler'>
     <returns>
      <reference idref='sax-error-handler'/>
     </returns>
    </method>
    <method name='setFeature'>
     <param name='featureId'>
      <reference idref='java-string'/>
     </param>
     <param name='state'>
      <primitive type='boolean'/>
     </param>
     <throws>
      <reference idref='sax-not-recognized-exception'/>
     </throws>
     <throws>
      <reference idref='sax-not-supported-exception'/>
     </throws>
    </method>
    <method name='getFeature'>
     <param name='featureId'>
      <reference idref='java-string'/>
     </param>
     <returns>
      <primitive type='boolean'/>
     </returns>
     <throws>
      <reference idref='sax-not-recognized-exception'/>
     </throws>
     <throws>
      <reference idref='sax-not-supported-exception'/>
     </throws>
    </method>
    <method name='setProperty'>
     <param name='propertyId'>
      <reference idref='java-string'/>
     </param>
     <param name='value'>
      <reference idref='java-object'/>
     </param>
     <throws>
      <reference idref='sax-not-recognized-exception'/>
     </throws>
     <throws>
      <reference idref='sax-not-supported-exception'/>
     </throws>
    </method>
    <method name='getProperty'>
     <param name='propertyId'>
      <reference idref='java-string'/>
     </param>
     <returns>
      <reference idref='java-object'/>
     </returns>
     <throws>
      <reference idref='sax-not-recognized-exception'/>
     </throws>
     <throws>
      <reference idref='sax-not-supported-exception'/>
     </throws>
    </method>
   </interface>
  </category>
 </types>

 <!-- Category: BASE -->
 <category name='Base' package='&package;.framework'>

  <interface id='configurable' name='XMLComponent'>
   <method name='reset'>
    <param name='configurationManager'>
     <reference idref='configuration-manager'/>
    </param>
    <throws>
     <reference idref='sax-exception'/>
    </throws>
   </method>
   <method name='setFeature'>
    <param name='featureId'>
     <reference idref='java-string'/>
    </param>
    <param name='state'>
     <primitive type='boolean'/>
    </param>
    <throws>
     <reference idref='sax-not-recognized-exception'/>
    </throws>
    <throws>
     <reference idref='sax-not-supported-exception'/>
    </throws>
   </method>
   <method name='setProperty'>
    <param name='propertyId'>
     <reference idref='java-string'/>
    </param>
    <param name='value'>
     <reference idref='java-object'/>
    </param>
    <throws>
     <reference idref='sax-not-recognized-exception'/>
    </throws>
    <throws>
     <reference idref='sax-not-supported-exception'/>
    </throws>
   </method>
  </interface>

  <interface id='configuration-manager' name='XMLComponentManager'>
   <method name='getFeature'>
    <param name='featureId'>
     <reference idref='java-string'/>
    </param>
    <returns>
     <primitive type='boolean'/>
    </returns>
    <throws>
     <reference idref='sax-not-recognized-exception'/>
    </throws>
    <throws>
     <reference idref='sax-not-supported-exception'/>
    </throws>
   </method>
   <method name='getProperty'>
    <param name='propertyId'>
     <reference idref='java-string'/>
    </param>
    <returns>
     <reference idref='java-object'/>
    </returns>
    <throws>
     <reference idref='sax-not-recognized-exception'/>
    </throws>
    <throws>
     <reference idref='sax-not-supported-exception'/>
    </throws>
   </method>
  </interface>

  <class id='string' name='XMLString'>
   <field name='ch' visibility='public'>
    <array>
     <primitive type='char'/>
    </array>
   </field>
   <field name='offset' visibility='public'>
    <primitive type='int'/>
   </field>
   <field name='length' visibility='public'>
    <primitive type='int'/>
   </field>
   <constructor/>
   <constructor>
    <param name='ch'>
     <array>
      <primitive type='char'/>
     </array>
    </param>
    <param name='offset'>
     <primitive type='int'/>
    </param>
    <param name='length'>
     <primitive type='int'/>
    </param>
   </constructor>
   <method name='setValues'>
    <param name='ch'>
     <array>
      <primitive type='char'/>
     </array>
    </param>
    <param name='offset'>
     <primitive type='int'/>
    </param>
    <param name='length'>
     <primitive type='int'/>
    </param>
   </method>
   <method name='clear'/>
   <method name='equals'>
    <param name='ch'>
     <array>
      <primitive type='char'/>
     </array>
    </param>
    <param name='offset'>
     <primitive type='int'/>
    </param>
    <param name='length'>
